//#line 2 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the blaser_pcl package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __blaser_pcl__LASEREXTRACTIONCONFIG_H__
#define __blaser_pcl__LASEREXTRACTIONCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace blaser_pcl
{
  class LaserExtractionConfigStatics;

  class LaserExtractionConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }

      virtual void clamp(LaserExtractionConfig &config, const LaserExtractionConfig &max, const LaserExtractionConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const LaserExtractionConfig &config1, const LaserExtractionConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, LaserExtractionConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const LaserExtractionConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, LaserExtractionConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const LaserExtractionConfig &config) const = 0;
      virtual void getValue(const LaserExtractionConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T LaserExtractionConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T (LaserExtractionConfig::* field);

      virtual void clamp(LaserExtractionConfig &config, const LaserExtractionConfig &max, const LaserExtractionConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const LaserExtractionConfig &config1, const LaserExtractionConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, LaserExtractionConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const LaserExtractionConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, LaserExtractionConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const LaserExtractionConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const LaserExtractionConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, LaserExtractionConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, LaserExtractionConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<LaserExtractionConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(LaserExtractionConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("simplecb_percent"==(*_i)->name){simplecb_percent = boost::any_cast<double>(val);}
        if("simplecb_enabled"==(*_i)->name){simplecb_enabled = boost::any_cast<bool>(val);}
      }
    }

    double simplecb_percent;
bool simplecb_enabled;

    bool state;
    std::string name;

    class RED_MASK_1_LO
{
  public:
    RED_MASK_1_LO()
    {
      state = true;
      name = "red_mask_1_lo";
    }

    void setParams(LaserExtractionConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("RMask_1_Lo_H"==(*_i)->name){RMask_1_Lo_H = boost::any_cast<int>(val);}
        if("RMask_1_Lo_S"==(*_i)->name){RMask_1_Lo_S = boost::any_cast<int>(val);}
        if("RMask_1_Lo_V"==(*_i)->name){RMask_1_Lo_V = boost::any_cast<int>(val);}
      }
    }

    int RMask_1_Lo_H;
int RMask_1_Lo_S;
int RMask_1_Lo_V;

    bool state;
    std::string name;

    
}red_mask_1_lo;

class RED_MASK_1_HI
{
  public:
    RED_MASK_1_HI()
    {
      state = true;
      name = "red_mask_1_hi";
    }

    void setParams(LaserExtractionConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("RMask_1_Hi_H"==(*_i)->name){RMask_1_Hi_H = boost::any_cast<int>(val);}
        if("RMask_1_Hi_S"==(*_i)->name){RMask_1_Hi_S = boost::any_cast<int>(val);}
        if("RMask_1_Hi_V"==(*_i)->name){RMask_1_Hi_V = boost::any_cast<int>(val);}
      }
    }

    int RMask_1_Hi_H;
int RMask_1_Hi_S;
int RMask_1_Hi_V;

    bool state;
    std::string name;

    
}red_mask_1_hi;

class RED_MASK_2_LO
{
  public:
    RED_MASK_2_LO()
    {
      state = true;
      name = "red_mask_2_lo";
    }

    void setParams(LaserExtractionConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("RMask_2_Lo_H"==(*_i)->name){RMask_2_Lo_H = boost::any_cast<int>(val);}
        if("RMask_2_Lo_S"==(*_i)->name){RMask_2_Lo_S = boost::any_cast<int>(val);}
        if("RMask_2_Lo_V"==(*_i)->name){RMask_2_Lo_V = boost::any_cast<int>(val);}
      }
    }

    int RMask_2_Lo_H;
int RMask_2_Lo_S;
int RMask_2_Lo_V;

    bool state;
    std::string name;

    
}red_mask_2_lo;

class RED_MASK_2_HI
{
  public:
    RED_MASK_2_HI()
    {
      state = true;
      name = "red_mask_2_hi";
    }

    void setParams(LaserExtractionConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("RMask_2_Hi_H"==(*_i)->name){RMask_2_Hi_H = boost::any_cast<int>(val);}
        if("RMask_2_Hi_S"==(*_i)->name){RMask_2_Hi_S = boost::any_cast<int>(val);}
        if("RMask_2_Hi_V"==(*_i)->name){RMask_2_Hi_V = boost::any_cast<int>(val);}
      }
    }

    int RMask_2_Hi_H;
int RMask_2_Hi_S;
int RMask_2_Hi_V;

    bool state;
    std::string name;

    
}red_mask_2_hi;

class NOISE_FILTERS
{
  public:
    NOISE_FILTERS()
    {
      state = true;
      name = "noise_filters";
    }

    void setParams(LaserExtractionConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("outlier_removel"==(*_i)->name){outlier_removel = boost::any_cast<bool>(val);}
        if("roi_r_percent"==(*_i)->name){roi_r_percent = boost::any_cast<double>(val);}
        if("roi_c_percent"==(*_i)->name){roi_c_percent = boost::any_cast<double>(val);}
      }
    }

    bool outlier_removel;
double roi_r_percent;
double roi_c_percent;

    bool state;
    std::string name;

    
}noise_filters;

}groups;



//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double simplecb_percent;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool simplecb_enabled;
//#line 12 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      int RMask_1_Lo_H;
//#line 13 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      int RMask_1_Lo_S;
//#line 14 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      int RMask_1_Lo_V;
//#line 17 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      int RMask_1_Hi_H;
//#line 18 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      int RMask_1_Hi_S;
//#line 19 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      int RMask_1_Hi_V;
//#line 22 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      int RMask_2_Lo_H;
//#line 23 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      int RMask_2_Lo_S;
//#line 24 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      int RMask_2_Lo_V;
//#line 27 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      int RMask_2_Hi_H;
//#line 28 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      int RMask_2_Hi_S;
//#line 29 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      int RMask_2_Hi_V;
//#line 32 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      bool outlier_removel;
//#line 33 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      double roi_r_percent;
//#line 34 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      double roi_c_percent;
//#line 228 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("LaserExtractionConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const LaserExtractionConfig &__max__ = __getMax__();
      const LaserExtractionConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const LaserExtractionConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const LaserExtractionConfig &__getDefault__();
    static const LaserExtractionConfig &__getMax__();
    static const LaserExtractionConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const LaserExtractionConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void LaserExtractionConfig::ParamDescription<std::string>::clamp(LaserExtractionConfig &config, const LaserExtractionConfig &max, const LaserExtractionConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class LaserExtractionConfigStatics
  {
    friend class LaserExtractionConfig;

    LaserExtractionConfigStatics()
    {
LaserExtractionConfig::GroupDescription<LaserExtractionConfig::DEFAULT, LaserExtractionConfig> Default("Default", "", 0, 0, true, &LaserExtractionConfig::groups);
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.simplecb_percent = 0.01;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.simplecb_percent = 10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.simplecb_percent = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LaserExtractionConfig::AbstractParamDescriptionConstPtr(new LaserExtractionConfig::ParamDescription<double>("simplecb_percent", "double", 0, "Color balance percent", "", &LaserExtractionConfig::simplecb_percent)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LaserExtractionConfig::AbstractParamDescriptionConstPtr(new LaserExtractionConfig::ParamDescription<double>("simplecb_percent", "double", 0, "Color balance percent", "", &LaserExtractionConfig::simplecb_percent)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.simplecb_enabled = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.simplecb_enabled = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.simplecb_enabled = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(LaserExtractionConfig::AbstractParamDescriptionConstPtr(new LaserExtractionConfig::ParamDescription<bool>("simplecb_enabled", "bool", 0, "Enable color balance", "", &LaserExtractionConfig::simplecb_enabled)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(LaserExtractionConfig::AbstractParamDescriptionConstPtr(new LaserExtractionConfig::ParamDescription<bool>("simplecb_enabled", "bool", 0, "Enable color balance", "", &LaserExtractionConfig::simplecb_enabled)));
LaserExtractionConfig::GroupDescription<LaserExtractionConfig::DEFAULT::RED_MASK_1_LO, LaserExtractionConfig::DEFAULT> red_mask_1_lo("red_mask_1_lo", "collapse", 0, 1, true, &LaserExtractionConfig::DEFAULT::red_mask_1_lo);
//#line 12 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      __min__.RMask_1_Lo_H = 0;
//#line 12 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      __max__.RMask_1_Lo_H = 180;
//#line 12 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      __default__.RMask_1_Lo_H = 92;
//#line 12 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      red_mask_1_lo.abstract_parameters.push_back(LaserExtractionConfig::AbstractParamDescriptionConstPtr(new LaserExtractionConfig::ParamDescription<int>("RMask_1_Lo_H", "int", 0, "Red laser line mask 1 Lo H", "", &LaserExtractionConfig::RMask_1_Lo_H)));
//#line 12 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      __param_descriptions__.push_back(LaserExtractionConfig::AbstractParamDescriptionConstPtr(new LaserExtractionConfig::ParamDescription<int>("RMask_1_Lo_H", "int", 0, "Red laser line mask 1 Lo H", "", &LaserExtractionConfig::RMask_1_Lo_H)));
//#line 13 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      __min__.RMask_1_Lo_S = 0;
//#line 13 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      __max__.RMask_1_Lo_S = 255;
//#line 13 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      __default__.RMask_1_Lo_S = 14;
//#line 13 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      red_mask_1_lo.abstract_parameters.push_back(LaserExtractionConfig::AbstractParamDescriptionConstPtr(new LaserExtractionConfig::ParamDescription<int>("RMask_1_Lo_S", "int", 0, "Red laser line mask 1 Lo S", "", &LaserExtractionConfig::RMask_1_Lo_S)));
//#line 13 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      __param_descriptions__.push_back(LaserExtractionConfig::AbstractParamDescriptionConstPtr(new LaserExtractionConfig::ParamDescription<int>("RMask_1_Lo_S", "int", 0, "Red laser line mask 1 Lo S", "", &LaserExtractionConfig::RMask_1_Lo_S)));
//#line 14 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      __min__.RMask_1_Lo_V = 0;
//#line 14 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      __max__.RMask_1_Lo_V = 255;
//#line 14 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      __default__.RMask_1_Lo_V = 0;
//#line 14 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      red_mask_1_lo.abstract_parameters.push_back(LaserExtractionConfig::AbstractParamDescriptionConstPtr(new LaserExtractionConfig::ParamDescription<int>("RMask_1_Lo_V", "int", 0, "Red laser line mask 1 Lo V", "", &LaserExtractionConfig::RMask_1_Lo_V)));
//#line 14 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      __param_descriptions__.push_back(LaserExtractionConfig::AbstractParamDescriptionConstPtr(new LaserExtractionConfig::ParamDescription<int>("RMask_1_Lo_V", "int", 0, "Red laser line mask 1 Lo V", "", &LaserExtractionConfig::RMask_1_Lo_V)));
//#line 124 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      red_mask_1_lo.convertParams();
//#line 124 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.groups.push_back(LaserExtractionConfig::AbstractGroupDescriptionConstPtr(new LaserExtractionConfig::GroupDescription<LaserExtractionConfig::DEFAULT::RED_MASK_1_LO, LaserExtractionConfig::DEFAULT>(red_mask_1_lo)));
//#line 124 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(LaserExtractionConfig::AbstractGroupDescriptionConstPtr(new LaserExtractionConfig::GroupDescription<LaserExtractionConfig::DEFAULT::RED_MASK_1_LO, LaserExtractionConfig::DEFAULT>(red_mask_1_lo)));
LaserExtractionConfig::GroupDescription<LaserExtractionConfig::DEFAULT::RED_MASK_1_HI, LaserExtractionConfig::DEFAULT> red_mask_1_hi("red_mask_1_hi", "collapse", 0, 2, true, &LaserExtractionConfig::DEFAULT::red_mask_1_hi);
//#line 17 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      __min__.RMask_1_Hi_H = 0;
//#line 17 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      __max__.RMask_1_Hi_H = 180;
//#line 17 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      __default__.RMask_1_Hi_H = 180;
//#line 17 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      red_mask_1_hi.abstract_parameters.push_back(LaserExtractionConfig::AbstractParamDescriptionConstPtr(new LaserExtractionConfig::ParamDescription<int>("RMask_1_Hi_H", "int", 0, "Red laser line mask 1 Hi H", "", &LaserExtractionConfig::RMask_1_Hi_H)));
//#line 17 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      __param_descriptions__.push_back(LaserExtractionConfig::AbstractParamDescriptionConstPtr(new LaserExtractionConfig::ParamDescription<int>("RMask_1_Hi_H", "int", 0, "Red laser line mask 1 Hi H", "", &LaserExtractionConfig::RMask_1_Hi_H)));
//#line 18 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      __min__.RMask_1_Hi_S = 0;
//#line 18 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      __max__.RMask_1_Hi_S = 255;
//#line 18 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      __default__.RMask_1_Hi_S = 255;
//#line 18 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      red_mask_1_hi.abstract_parameters.push_back(LaserExtractionConfig::AbstractParamDescriptionConstPtr(new LaserExtractionConfig::ParamDescription<int>("RMask_1_Hi_S", "int", 0, "Red laser line mask 1 Hi S", "", &LaserExtractionConfig::RMask_1_Hi_S)));
//#line 18 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      __param_descriptions__.push_back(LaserExtractionConfig::AbstractParamDescriptionConstPtr(new LaserExtractionConfig::ParamDescription<int>("RMask_1_Hi_S", "int", 0, "Red laser line mask 1 Hi S", "", &LaserExtractionConfig::RMask_1_Hi_S)));
//#line 19 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      __min__.RMask_1_Hi_V = 0;
//#line 19 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      __max__.RMask_1_Hi_V = 255;
//#line 19 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      __default__.RMask_1_Hi_V = 255;
//#line 19 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      red_mask_1_hi.abstract_parameters.push_back(LaserExtractionConfig::AbstractParamDescriptionConstPtr(new LaserExtractionConfig::ParamDescription<int>("RMask_1_Hi_V", "int", 0, "Red laser line mask 1 Hi V", "", &LaserExtractionConfig::RMask_1_Hi_V)));
//#line 19 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      __param_descriptions__.push_back(LaserExtractionConfig::AbstractParamDescriptionConstPtr(new LaserExtractionConfig::ParamDescription<int>("RMask_1_Hi_V", "int", 0, "Red laser line mask 1 Hi V", "", &LaserExtractionConfig::RMask_1_Hi_V)));
//#line 124 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      red_mask_1_hi.convertParams();
//#line 124 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.groups.push_back(LaserExtractionConfig::AbstractGroupDescriptionConstPtr(new LaserExtractionConfig::GroupDescription<LaserExtractionConfig::DEFAULT::RED_MASK_1_HI, LaserExtractionConfig::DEFAULT>(red_mask_1_hi)));
//#line 124 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(LaserExtractionConfig::AbstractGroupDescriptionConstPtr(new LaserExtractionConfig::GroupDescription<LaserExtractionConfig::DEFAULT::RED_MASK_1_HI, LaserExtractionConfig::DEFAULT>(red_mask_1_hi)));
LaserExtractionConfig::GroupDescription<LaserExtractionConfig::DEFAULT::RED_MASK_2_LO, LaserExtractionConfig::DEFAULT> red_mask_2_lo("red_mask_2_lo", "collapse", 0, 3, true, &LaserExtractionConfig::DEFAULT::red_mask_2_lo);
//#line 22 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      __min__.RMask_2_Lo_H = 0;
//#line 22 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      __max__.RMask_2_Lo_H = 180;
//#line 22 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      __default__.RMask_2_Lo_H = 0;
//#line 22 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      red_mask_2_lo.abstract_parameters.push_back(LaserExtractionConfig::AbstractParamDescriptionConstPtr(new LaserExtractionConfig::ParamDescription<int>("RMask_2_Lo_H", "int", 0, "Red laser line mask 2 Lo H", "", &LaserExtractionConfig::RMask_2_Lo_H)));
//#line 22 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      __param_descriptions__.push_back(LaserExtractionConfig::AbstractParamDescriptionConstPtr(new LaserExtractionConfig::ParamDescription<int>("RMask_2_Lo_H", "int", 0, "Red laser line mask 2 Lo H", "", &LaserExtractionConfig::RMask_2_Lo_H)));
//#line 23 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      __min__.RMask_2_Lo_S = 0;
//#line 23 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      __max__.RMask_2_Lo_S = 255;
//#line 23 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      __default__.RMask_2_Lo_S = 100;
//#line 23 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      red_mask_2_lo.abstract_parameters.push_back(LaserExtractionConfig::AbstractParamDescriptionConstPtr(new LaserExtractionConfig::ParamDescription<int>("RMask_2_Lo_S", "int", 0, "Red laser line mask 2 Lo S", "", &LaserExtractionConfig::RMask_2_Lo_S)));
//#line 23 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      __param_descriptions__.push_back(LaserExtractionConfig::AbstractParamDescriptionConstPtr(new LaserExtractionConfig::ParamDescription<int>("RMask_2_Lo_S", "int", 0, "Red laser line mask 2 Lo S", "", &LaserExtractionConfig::RMask_2_Lo_S)));
//#line 24 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      __min__.RMask_2_Lo_V = 0;
//#line 24 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      __max__.RMask_2_Lo_V = 255;
//#line 24 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      __default__.RMask_2_Lo_V = 150;
//#line 24 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      red_mask_2_lo.abstract_parameters.push_back(LaserExtractionConfig::AbstractParamDescriptionConstPtr(new LaserExtractionConfig::ParamDescription<int>("RMask_2_Lo_V", "int", 0, "Red laser line mask 2 Lo V", "", &LaserExtractionConfig::RMask_2_Lo_V)));
//#line 24 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      __param_descriptions__.push_back(LaserExtractionConfig::AbstractParamDescriptionConstPtr(new LaserExtractionConfig::ParamDescription<int>("RMask_2_Lo_V", "int", 0, "Red laser line mask 2 Lo V", "", &LaserExtractionConfig::RMask_2_Lo_V)));
//#line 124 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      red_mask_2_lo.convertParams();
//#line 124 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.groups.push_back(LaserExtractionConfig::AbstractGroupDescriptionConstPtr(new LaserExtractionConfig::GroupDescription<LaserExtractionConfig::DEFAULT::RED_MASK_2_LO, LaserExtractionConfig::DEFAULT>(red_mask_2_lo)));
//#line 124 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(LaserExtractionConfig::AbstractGroupDescriptionConstPtr(new LaserExtractionConfig::GroupDescription<LaserExtractionConfig::DEFAULT::RED_MASK_2_LO, LaserExtractionConfig::DEFAULT>(red_mask_2_lo)));
LaserExtractionConfig::GroupDescription<LaserExtractionConfig::DEFAULT::RED_MASK_2_HI, LaserExtractionConfig::DEFAULT> red_mask_2_hi("red_mask_2_hi", "collapse", 0, 4, true, &LaserExtractionConfig::DEFAULT::red_mask_2_hi);
//#line 27 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      __min__.RMask_2_Hi_H = 0;
//#line 27 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      __max__.RMask_2_Hi_H = 180;
//#line 27 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      __default__.RMask_2_Hi_H = 43;
//#line 27 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      red_mask_2_hi.abstract_parameters.push_back(LaserExtractionConfig::AbstractParamDescriptionConstPtr(new LaserExtractionConfig::ParamDescription<int>("RMask_2_Hi_H", "int", 0, "Red laser line mask 2 Hi H", "", &LaserExtractionConfig::RMask_2_Hi_H)));
//#line 27 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      __param_descriptions__.push_back(LaserExtractionConfig::AbstractParamDescriptionConstPtr(new LaserExtractionConfig::ParamDescription<int>("RMask_2_Hi_H", "int", 0, "Red laser line mask 2 Hi H", "", &LaserExtractionConfig::RMask_2_Hi_H)));
//#line 28 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      __min__.RMask_2_Hi_S = 0;
//#line 28 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      __max__.RMask_2_Hi_S = 255;
//#line 28 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      __default__.RMask_2_Hi_S = 191;
//#line 28 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      red_mask_2_hi.abstract_parameters.push_back(LaserExtractionConfig::AbstractParamDescriptionConstPtr(new LaserExtractionConfig::ParamDescription<int>("RMask_2_Hi_S", "int", 0, "Red laser line mask 2 Hi S", "", &LaserExtractionConfig::RMask_2_Hi_S)));
//#line 28 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      __param_descriptions__.push_back(LaserExtractionConfig::AbstractParamDescriptionConstPtr(new LaserExtractionConfig::ParamDescription<int>("RMask_2_Hi_S", "int", 0, "Red laser line mask 2 Hi S", "", &LaserExtractionConfig::RMask_2_Hi_S)));
//#line 29 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      __min__.RMask_2_Hi_V = 0;
//#line 29 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      __max__.RMask_2_Hi_V = 255;
//#line 29 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      __default__.RMask_2_Hi_V = 202;
//#line 29 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      red_mask_2_hi.abstract_parameters.push_back(LaserExtractionConfig::AbstractParamDescriptionConstPtr(new LaserExtractionConfig::ParamDescription<int>("RMask_2_Hi_V", "int", 0, "Red laser line mask 2 Hi V", "", &LaserExtractionConfig::RMask_2_Hi_V)));
//#line 29 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      __param_descriptions__.push_back(LaserExtractionConfig::AbstractParamDescriptionConstPtr(new LaserExtractionConfig::ParamDescription<int>("RMask_2_Hi_V", "int", 0, "Red laser line mask 2 Hi V", "", &LaserExtractionConfig::RMask_2_Hi_V)));
//#line 124 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      red_mask_2_hi.convertParams();
//#line 124 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.groups.push_back(LaserExtractionConfig::AbstractGroupDescriptionConstPtr(new LaserExtractionConfig::GroupDescription<LaserExtractionConfig::DEFAULT::RED_MASK_2_HI, LaserExtractionConfig::DEFAULT>(red_mask_2_hi)));
//#line 124 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(LaserExtractionConfig::AbstractGroupDescriptionConstPtr(new LaserExtractionConfig::GroupDescription<LaserExtractionConfig::DEFAULT::RED_MASK_2_HI, LaserExtractionConfig::DEFAULT>(red_mask_2_hi)));
LaserExtractionConfig::GroupDescription<LaserExtractionConfig::DEFAULT::NOISE_FILTERS, LaserExtractionConfig::DEFAULT> noise_filters("noise_filters", "collapse", 0, 5, true, &LaserExtractionConfig::DEFAULT::noise_filters);
//#line 32 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      __min__.outlier_removel = 0;
//#line 32 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      __max__.outlier_removel = 1;
//#line 32 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      __default__.outlier_removel = 1;
//#line 32 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      noise_filters.abstract_parameters.push_back(LaserExtractionConfig::AbstractParamDescriptionConstPtr(new LaserExtractionConfig::ParamDescription<bool>("outlier_removel", "bool", 0, "Enable outlier removal", "", &LaserExtractionConfig::outlier_removel)));
//#line 32 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      __param_descriptions__.push_back(LaserExtractionConfig::AbstractParamDescriptionConstPtr(new LaserExtractionConfig::ParamDescription<bool>("outlier_removel", "bool", 0, "Enable outlier removal", "", &LaserExtractionConfig::outlier_removel)));
//#line 33 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      __min__.roi_r_percent = 0.0;
//#line 33 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      __max__.roi_r_percent = 0.99;
//#line 33 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      __default__.roi_r_percent = 0.078125;
//#line 33 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      noise_filters.abstract_parameters.push_back(LaserExtractionConfig::AbstractParamDescriptionConstPtr(new LaserExtractionConfig::ParamDescription<double>("roi_r_percent", "double", 0, "ROI row top cap", "", &LaserExtractionConfig::roi_r_percent)));
//#line 33 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      __param_descriptions__.push_back(LaserExtractionConfig::AbstractParamDescriptionConstPtr(new LaserExtractionConfig::ParamDescription<double>("roi_r_percent", "double", 0, "ROI row top cap", "", &LaserExtractionConfig::roi_r_percent)));
//#line 34 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      __min__.roi_c_percent = 0.0;
//#line 34 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      __max__.roi_c_percent = 0.5;
//#line 34 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      __default__.roi_c_percent = 0.015625;
//#line 34 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      noise_filters.abstract_parameters.push_back(LaserExtractionConfig::AbstractParamDescriptionConstPtr(new LaserExtractionConfig::ParamDescription<double>("roi_c_percent", "double", 0, "ROI col side cap (R/L)", "", &LaserExtractionConfig::roi_c_percent)));
//#line 34 "/home/arti/Medical-DVRK-AR/src/blaser-ros/blaser_pcl/cfg/LaserExtraction.cfg"
      __param_descriptions__.push_back(LaserExtractionConfig::AbstractParamDescriptionConstPtr(new LaserExtractionConfig::ParamDescription<double>("roi_c_percent", "double", 0, "ROI col side cap (R/L)", "", &LaserExtractionConfig::roi_c_percent)));
//#line 124 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      noise_filters.convertParams();
//#line 124 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.groups.push_back(LaserExtractionConfig::AbstractGroupDescriptionConstPtr(new LaserExtractionConfig::GroupDescription<LaserExtractionConfig::DEFAULT::NOISE_FILTERS, LaserExtractionConfig::DEFAULT>(noise_filters)));
//#line 124 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(LaserExtractionConfig::AbstractGroupDescriptionConstPtr(new LaserExtractionConfig::GroupDescription<LaserExtractionConfig::DEFAULT::NOISE_FILTERS, LaserExtractionConfig::DEFAULT>(noise_filters)));
//#line 245 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 245 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(LaserExtractionConfig::AbstractGroupDescriptionConstPtr(new LaserExtractionConfig::GroupDescription<LaserExtractionConfig::DEFAULT, LaserExtractionConfig>(Default)));
//#line 366 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<LaserExtractionConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<LaserExtractionConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<LaserExtractionConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    LaserExtractionConfig __max__;
    LaserExtractionConfig __min__;
    LaserExtractionConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const LaserExtractionConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static LaserExtractionConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &LaserExtractionConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const LaserExtractionConfig &LaserExtractionConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const LaserExtractionConfig &LaserExtractionConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const LaserExtractionConfig &LaserExtractionConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<LaserExtractionConfig::AbstractParamDescriptionConstPtr> &LaserExtractionConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<LaserExtractionConfig::AbstractGroupDescriptionConstPtr> &LaserExtractionConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const LaserExtractionConfigStatics *LaserExtractionConfig::__get_statics__()
  {
    const static LaserExtractionConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = LaserExtractionConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __LASEREXTRACTIONRECONFIGURATOR_H__
