// Generated by gencpp from file blaser_pcl/VoxelGridStitchResponse.msg
// DO NOT EDIT!


#ifndef BLASER_PCL_MESSAGE_VOXELGRIDSTITCHRESPONSE_H
#define BLASER_PCL_MESSAGE_VOXELGRIDSTITCHRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace blaser_pcl
{
template <class ContainerAllocator>
struct VoxelGridStitchResponse_
{
  typedef VoxelGridStitchResponse_<ContainerAllocator> Type;

  VoxelGridStitchResponse_()
    : status(0)  {
    }
  VoxelGridStitchResponse_(const ContainerAllocator& _alloc)
    : status(0)  {
  (void)_alloc;
    }



   typedef int64_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::blaser_pcl::VoxelGridStitchResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::blaser_pcl::VoxelGridStitchResponse_<ContainerAllocator> const> ConstPtr;

}; // struct VoxelGridStitchResponse_

typedef ::blaser_pcl::VoxelGridStitchResponse_<std::allocator<void> > VoxelGridStitchResponse;

typedef boost::shared_ptr< ::blaser_pcl::VoxelGridStitchResponse > VoxelGridStitchResponsePtr;
typedef boost::shared_ptr< ::blaser_pcl::VoxelGridStitchResponse const> VoxelGridStitchResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::blaser_pcl::VoxelGridStitchResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::blaser_pcl::VoxelGridStitchResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace blaser_pcl

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::blaser_pcl::VoxelGridStitchResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::blaser_pcl::VoxelGridStitchResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::blaser_pcl::VoxelGridStitchResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::blaser_pcl::VoxelGridStitchResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::blaser_pcl::VoxelGridStitchResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::blaser_pcl::VoxelGridStitchResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::blaser_pcl::VoxelGridStitchResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4107476a6271fc2684d94be17d33f854";
  }

  static const char* value(const ::blaser_pcl::VoxelGridStitchResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4107476a6271fc26ULL;
  static const uint64_t static_value2 = 0x84d94be17d33f854ULL;
};

template<class ContainerAllocator>
struct DataType< ::blaser_pcl::VoxelGridStitchResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "blaser_pcl/VoxelGridStitchResponse";
  }

  static const char* value(const ::blaser_pcl::VoxelGridStitchResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::blaser_pcl::VoxelGridStitchResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 status\n\
";
  }

  static const char* value(const ::blaser_pcl::VoxelGridStitchResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::blaser_pcl::VoxelGridStitchResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VoxelGridStitchResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::blaser_pcl::VoxelGridStitchResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::blaser_pcl::VoxelGridStitchResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<int64_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BLASER_PCL_MESSAGE_VOXELGRIDSTITCHRESPONSE_H
