// Generated by gencpp from file blaser_pcl/VoxelGridStitchRequest.msg
// DO NOT EDIT!


#ifndef BLASER_PCL_MESSAGE_VOXELGRIDSTITCHREQUEST_H
#define BLASER_PCL_MESSAGE_VOXELGRIDSTITCHREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace blaser_pcl
{
template <class ContainerAllocator>
struct VoxelGridStitchRequest_
{
  typedef VoxelGridStitchRequest_<ContainerAllocator> Type;

  VoxelGridStitchRequest_()
    : start(0)
    , pause(0)
    , clear(0)
    , leaf_size(0.0)  {
    }
  VoxelGridStitchRequest_(const ContainerAllocator& _alloc)
    : start(0)
    , pause(0)
    , clear(0)
    , leaf_size(0.0)  {
  (void)_alloc;
    }



   typedef int8_t _start_type;
  _start_type start;

   typedef int8_t _pause_type;
  _pause_type pause;

   typedef int8_t _clear_type;
  _clear_type clear;

   typedef double _leaf_size_type;
  _leaf_size_type leaf_size;





  typedef boost::shared_ptr< ::blaser_pcl::VoxelGridStitchRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::blaser_pcl::VoxelGridStitchRequest_<ContainerAllocator> const> ConstPtr;

}; // struct VoxelGridStitchRequest_

typedef ::blaser_pcl::VoxelGridStitchRequest_<std::allocator<void> > VoxelGridStitchRequest;

typedef boost::shared_ptr< ::blaser_pcl::VoxelGridStitchRequest > VoxelGridStitchRequestPtr;
typedef boost::shared_ptr< ::blaser_pcl::VoxelGridStitchRequest const> VoxelGridStitchRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::blaser_pcl::VoxelGridStitchRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::blaser_pcl::VoxelGridStitchRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace blaser_pcl

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::blaser_pcl::VoxelGridStitchRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::blaser_pcl::VoxelGridStitchRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::blaser_pcl::VoxelGridStitchRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::blaser_pcl::VoxelGridStitchRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::blaser_pcl::VoxelGridStitchRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::blaser_pcl::VoxelGridStitchRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::blaser_pcl::VoxelGridStitchRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f9b2baaa3ec3d1724df9a4f441fb6f00";
  }

  static const char* value(const ::blaser_pcl::VoxelGridStitchRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf9b2baaa3ec3d172ULL;
  static const uint64_t static_value2 = 0x4df9a4f441fb6f00ULL;
};

template<class ContainerAllocator>
struct DataType< ::blaser_pcl::VoxelGridStitchRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "blaser_pcl/VoxelGridStitchRequest";
  }

  static const char* value(const ::blaser_pcl::VoxelGridStitchRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::blaser_pcl::VoxelGridStitchRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 start\n\
int8 pause\n\
int8 clear\n\
float64 leaf_size\n\
";
  }

  static const char* value(const ::blaser_pcl::VoxelGridStitchRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::blaser_pcl::VoxelGridStitchRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.start);
      stream.next(m.pause);
      stream.next(m.clear);
      stream.next(m.leaf_size);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VoxelGridStitchRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::blaser_pcl::VoxelGridStitchRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::blaser_pcl::VoxelGridStitchRequest_<ContainerAllocator>& v)
  {
    s << indent << "start: ";
    Printer<int8_t>::stream(s, indent + "  ", v.start);
    s << indent << "pause: ";
    Printer<int8_t>::stream(s, indent + "  ", v.pause);
    s << indent << "clear: ";
    Printer<int8_t>::stream(s, indent + "  ", v.clear);
    s << indent << "leaf_size: ";
    Printer<double>::stream(s, indent + "  ", v.leaf_size);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BLASER_PCL_MESSAGE_VOXELGRIDSTITCHREQUEST_H
